### PR TITLE
Update boost git tag in GHA

### PR DESCRIPTION
**Pull request by sdarwin**
Since the dedicated servers are shared by all jobs and all branches, this change will affect those other branches as well. I have cleared the cache on the servers. Let's observe how the GHA jobs run.

### CODE REVIEW

**Comment by joaquintides** [comment]
Looks like dedicated server runs are failing?

**Comment by joaquintides** [comment]
Working now. Thank you!

**Comment by joaquintides** [comment]
I spoke too fast. In Windows include paths are not ok or something:
```
uint32.cpp(9): fatal error C1083: Cannot open include file: 'boost/algorithm/minmax_element.hpp': No such file or directory
```

**Comment by joaquintides** [comment]
Managed to fix it on my own :-) bc06538e0ab532dc40f89f4317d185c7f5bbdec5
Thank you!

**Comment by sdarwin** [comment]
Glad you fixed it!   That is a mystery since `setlocal enabledelayedexpansion` should enable run-time variable expansion with the !bang! format.

**Pull request merged**
